# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1164, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 60, 751, 286))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_cmd = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_cmd.setContentsMargins(20, 10, 20, 10)
        self.gridLayout_cmd.setObjectName("gridLayout_cmd")
        self.adjust_no = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.adjust_no.setObjectName("adjust_no")
        self.gridLayout_cmd.addWidget(self.adjust_no, 1, 2, 1, 1)
        self.adjust_yes = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.adjust_yes.setObjectName("adjust_yes")
        self.gridLayout_cmd.addWidget(self.adjust_yes, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_cmd.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_left.sizePolicy().hasHeightForWidth())
        self.pushButton_left.setSizePolicy(sizePolicy)
        self.pushButton_left.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_left.setFont(font)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_cmd.addWidget(self.pushButton_left, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_right.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_right.setFont(font)
        self.pushButton_right.setAutoRepeatInterval(100)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_cmd.addWidget(self.pushButton_right, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_cmd.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_cmd.setColumnStretch(0, 1)
        self.gridLayout_cmd.setColumnStretch(1, 4)
        self.gridLayout_cmd.setColumnStretch(2, 1)
        self.gridLayout_cmd.setRowStretch(0, 1)
        self.gridLayout_cmd.setRowStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.adjust_no.setText(_translate("Form", "Cancel"))
        self.adjust_yes.setText(_translate("Form", "OK"))
        self.pushButton_left.setText(_translate("Form", "左转"))
        self.pushButton_right.setText(_translate("Form", "右转"))
